# ===============================
# Datasource
# ===============================
spring.datasource.url=jdbc:postgresql://192.168.122.174:5432/user_services
spring.datasource.username=delmas
spring.datasource.password=delmasadmin


# ===============================
# JPA / Hibernate
# ===============================

#Hibernate crée les tables manquantes, ajoute les colonnes manquantes, met à jour le schéma si tes entités changent
#en PROD (validate) = Hibernate vérifie que le schéma de la base de données correspond exactement à tes entités JPA, sans rien modifier
spring.jpa.hibernate.ddl-auto=validate

spring.jpa.show-sql=false

#indique à Hibernate quel SGBD est utilisé
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect


#=======
### LOGS
#=======
spring.jpa.properties.hibernate.format_sql=true

# En Développement
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE


# ===============================
# PROMETHEUS
# ===============================
management.metrics.tags.application=user_services
management.metrics.tags.env=dev
management.endpoints.web.exposure.include=health,info,prometheus
management.endpoint.health.show-details=always
management.endpoint.prometheus.access=read-only
management.metrics.distribution.percentiles-histogram.http.server.requests=true


# ===============================
# TEMPO
# ===============================
management.otlp.metrics.export.enabled: false
management.opentelemetry.tracing.export.otlp.endpoint=http://tempo:4318/v1/traces
management.tracing.export.enabled=true

# 100% des traces (à utiliser uniquement en environnement de développement)
management.tracing.sampling.probability=1.0

management.opentelemetry.tracing.export.otlp.connect-timeout=5s


# ===============================
# LOG CORRELATION
# ===============================
#Pour corrélation Loki ↔ Tempo :
logging.pattern.level=%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]