# ===============================
# Datasource
# ===============================
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

# Pool recommandé en production
spring.datasource.hikari.maximum-pool-size=20
spring.datasource.hikari.minimum-idle=5
spring.datasource.hikari.idle-timeout=30000
spring.datasource.hikari.max-lifetime=1800000
spring.datasource.hikari.connection-timeout=30000

# ===============================
# JPA / Hibernate
# ===============================

#Hibernate crée les tables manquantes, ajoute les colonnes manquantes, met à jour le schéma si tes entités changent
#(validate) = Hibernate vérifie que le schéma de la base de données correspond exactement à tes entités JPA, sans rien modifier
spring.jpa.hibernate.ddl-auto=validate

spring.jpa.show-sql=false

#indique à Hibernate quel SGBD est utilisé
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

#=======
### LOGS
#=======
spring.jpa.properties.hibernate.format_sql=false
logging.level.org.hibernate.SQL=INFO
logging.level.root=INFO

# ===============================
# PROMETHEUS
# ===============================
management.metrics.tags.application=user_services
management.metrics.tags.env=prod
management.endpoints.web.exposure.include=health,info,prometheus
management.endpoint.health.show-details=never
management.endpoint.prometheus.access=read-only
management.metrics.distribution.percentiles-histogram.http.server.requests=true

# ===============================
# TEMPO
# ===============================
management.otlp.metrics.export.enabled=false
management.opentelemetry.tracing.export.otlp.endpoint=${OTEL_EXPORTER_OTLP_ENDPOINT}
management.tracing.export.enabled=true

# 100% des traces (à utiliser uniquement en environnement de développement)
management.tracing.sampling.probability=0.1

management.opentelemetry.tracing.export.otlp.connect-timeout=5s

# ===============================
# LOG CORRELATION
# ===============================
#Pour corrélation Loki ↔ Tempo :
logging.pattern.level=%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]


# ===============================
# OpenAPI (Swagger)
# ===============================
springdoc.swagger-ui.tryItOutEnabled=true
springdoc.swagger-ui.filter=true