CREATE TABLE users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email VARCHAR(255) NOT NULL UNIQUE,
    first_name VARCHAR(255) NOT NULL,
    last_name VARCHAR(255) NOT NULL,
    active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- Les Index (remarqué : création automatique lors du lancement)
--CREATE UNIQUE INDEX users_pkey ON public.users USING btree (id);
--CREATE UNIQUE INDEX uk6dotkott2kjsp8vw4d0m25fb7 ON public.users USING btree (email);


-- Les Séquences (remarqué : création automatique lors du lancement)
--CREATE SEQUENCE public.users_id_seq START WITH 1 INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 NO CYCLE;